# Content configuration with conditioning inputs.
context: >
  representative population of youth aged 14 to 21 as of December 31, 1978
  (that is, born between 1957 and 1964), residing in the United
  States on January 1, 1979.

population_context:
  reference_year: 1979
  age_range: [14, 70]
  region: United States

input_variables:
  gender:
    name: Gender
    type: static
    description: Sex of Respondent

  race:
    name: Race
    type: static
    description: Respondent's Racial/ethnic Identification

  immigrant_status:
    name: Immigrant Status
    type: static
    description: Respondent's Immigration Status

output_variables:
  self_rated_health:
    name: Self-Rated Health
    type: static
    description: Respondent's Self-Assessment of General Health
    allowed:
      - Excellent
      - Very Good
      - Good
      - Fair
      - Poor

  self_rated_memory:
    name: Self-Rated Memory
    type: static
    description: Respondent's Self-Rating of Memory, Which Is an Indicator of Cognitive Skills
    allowed:
      - Excellent
      - Very Good
      - Good
      - Fair
      - Poor
  high_educ:
    name: Education
    type: staic
    description: Highest level of education that respondent has completed and get credit for lifelong.
    allowed:
      - less than high school
      - high school
      - college and above

  high_inccat:
    name: Income
    type: static
    description: Highest Income from Wages, Salary, Commissions, or Tips from All Jobs in the Calendar Year Lifelong.
    allowed:
      - lower than 5000
      - 5000 - 9999
      - 10000 - 19999
      - 20000 - 49999
      - 50000+

  educ:
    name: Education
    type: sequential
    description: Highest level of education that respondent has completed and get credit for at the age.
    allowed:
      - less than high school
      - high school
      - college and above


  inccat:
    name: Income
    type: sequential
    description: Income from Wages, Salary, Commissions, or Tips from All Jobs in the Past Calendar Year
    allowed:
      - lower than 5000
      - 5000 - 9999
      - 10000 - 19999
      - 20000 - 49999
      - 50000+

  occ:
    name: Occupation
    type: sequential
    description: Occupation Category, using the classification scheme of CPSOCC70
    allowed:
      - PROFESSIONAL, TECHNICAL AND KINDRED
      - OPERATIVES AND KINDRED
      - MANAGERS, OFFICIALS AND PROPRIETORS
      - SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD
      - CLERICAL AND KINDRED
      - CRAFTSMEN, FOREMEN AND KINDRED
      - SALES WORKERS
      - LABORERS, EXCEPT FARM
      - PRIVATE HOUSEHOLD
      - FARM LABORERS AND FOREMAN
      - NA

  age_at_first_birth:
    name: Age at First Childbirth
    type: static
    description: Age when the respondent had their first child.
    allowed:
      type: numeric
      min: 17.0
      max: 63.0
      special:
        - No Childbearing

  AGE1M:
    name: Age at First Marriage
    type: static
    description: Age when the respondent first got married.
    allowed:
      type: numeric
      min: 13.0
      max: 62.0
      special:
        - Never Married

postprocess_modules:
  - age_completed_education

postprocess_description: >
  Adds age_completed_education to capture when education stabilizes.

original_data:
  source: "NLSY79"
  description: >
    National Longitudinal Survey of Youth 1979 cohort,
    which samples U.S. residents aged 14–21 as of December 31, 1978.
  file: "./real_data/nlsy1023.csv"
