# ===============================================
# LEVEL 4 — Event Order Consistency Bootstrap Config
# ===============================================

real_csv: /home/yx5888/Workspace/AI4SS-Evaluation/simulated_data_1117/addhealth/sim_profiles_deepseek-deepseek-chat_temp1_top1.0/sampled_inputs_deepseek-deepseek-chat_temp1_top1.0.csv
sim_csv: /home/yx5888/Workspace/AI4SS-Evaluation/simulated_data_1117/addhealth/sim_profiles_deepseek-deepseek-chat_temp1_top1.0/sim_profiles_deepseek-deepseek-chat_temp1_top1.0.csv

out_dir: "./debugdeepseek"

# === Event Variables (chronological order test) ===
event_variables:
  age_started_work:
    name: W
  age_at_first_sex:
    name: S
  age_at_first_marriage:
    name: M
  # age_completed_education:
  #   name: E
  # AGE1M:
  #   name: M
  #   value_map:
  #     Never Married: inf
  #     "": null
  # age_at_first_birth:
  #   name: B
  #   value_map:
  #     No Childbearing: inf
  #     "": null

# === Bootstrap Settings ===
bootstrap_B: 10    # Number of bootstrap iterations
alpha: 0.05              # Significance level (e.g., 0.05 → 95% CI)
bootstrap_sample_ratio: null  # Sampling ratio per iteration (unused if sample_n is set)
bootstrap_sample_n: 500        # Fixed sample size per bootstrap draw