variables:
  XA1: {type: categorical}
  XA2: {type: categorical}
  XA3: {type: categorical}
  XA4: {type: categorical}
  XA5: {type: categorical}
  XA6: {type: categorical}
  XB1: {type: categorical}
  XB2: {type: categorical}
  XB3: {type: categorical}
  XB4: {type: categorical}
  XB5: {type: categorical}
  XB6: {type: categorical}
  XC1: {type: categorical}
  XC2: {type: categorical}
  XC3: {type: categorical}
  XC4: {type: categorical}
  XC5: {type: categorical}
  XC6: {type: categorical}
  B101_1: {type: numeric}
  B102_1: {type: numeric}
  B103_1: {type: numeric}
