real_csv: /home/yx5888/Workspace/AI4SS-Evaluation/simulated_data_1117/cps_1980/sim_profiles_anthropic-claude-3-haiku_temp1_top1.0/sampled_inputs_anthropic-claude-3-haiku_temp1_top1.0.csv
sim_csv: /home/yx5888/Workspace/AI4SS-Evaluation/simulated_data_1117/cps_1980/sim_profiles_anthropic-claude-3-haiku_temp1_top1.0/sim_profiles_anthropic-claude-3-haiku_temp1_top1.0.csv
out_dir: "./debug_cps"

bootstrap_B: 10
alpha: 0.05
bootstrap_sample_n: 1000

variables:
  age:
    name: Age
    type: numeric
    input: true    
    description: Age
    domain: Demography
    allowed:
      min: 0
      max: 99

  gender:
    name: Gender
    input: true
    type: categorical
    description: Sex
    domain: Demography
    allowed:
      - Female
      - Male

  race:
    name: Race
    input: true
    type: categorical
    description: Racial/ethnic identification
    domain: Demography
    allowed:
      - Black
      - Hispanic
      - Non-Black, Non-Hispanic

  marital_status:
    name: Marital Status
    type: categorical
    description: Marital status
    domain: Marriage
    allowed:
      - Married
      - Divorced/widowed
      - Single

  child_number:
    name: Child Number
    type: numeric
    description: Number of child ever born
    domain: Marriage
    allowed:
      min: 0
      max: 9

  age_first_childbirth:
    name: Age at First Childbirth
    type: numeric
    description: Age at first childbirth
    domain: Marriage
    allowed:
      min: 12
      max: 90

  education:
    name: Education
    type: categorical
    description: Educational attainment
    domain: SES
    allowed:
      - Less than high school
      - High school
      - College and above

  # laborforce:
  #   name: Labor Force Status
  #   type: categorical
  #   description: Whether the respondent participated in the labor force
  #   domain: SES
  #   allowed:
  #     - Not in the labor force
  #     - In the labor force

  occupation:
    name: Occupation
    type: categorical
    description: Occupation
    domain: SES
    allowed:
      - Managerial Occupations
      - Professional Specialty Occupations
      - Technicians and Related Support Occupations
      - Sales Occupations
      - Clerical and Administrative Support Occupations
      - Service Occupations
      - Farming, Forestry, and Fishing Occupations
      - Precision Production, Craft, and Repair Occupations
      - Operators, Fabricators, and Laborers
      - Military Occupations
    drop_values:
      - Unemployed

  income:
    name: Income
    type: numeric
    description: Total personal income last year
    domain: SES
    allowed:
      min: 0
      max: 9999997

  poverty_status:
    name: Poverty Status
    type: categorical
    description: Poverty status
    domain: SES
    allowed:
      - Below poverty line
      - Above poverty line