real_csv: "/home/yx5888/Workspace/AI4SS_Evaluation_local/Simulated_modified/sampled_inputs_gpt-4_temp1.0_top1.0.csv"
sim_csv: "/home/yx5888/Workspace/AI4SS_Evaluation_local/Simulated_modified/sim_profiles_gpt-4_temp1.0_top1.0.csv"
out_dir: "./1111"

bootstrap_B: 10
alpha: 0.05
bootstrap_sample_n: 500

variables:
  gender:
    type: categorical
    name: "Gender"
    input: true

  race:
    type: categorical
    name: "Race"
    input: true

  immigrant_status:
    type: categorical
    name: "Immigrant Status"
    input: true

  self_rated_health:
    type: categorical
    name: "Self-rated Health"

  self_rated_memory:
    type: categorical
    name: "Self-rated Memory"

  age_at_first_birth:
    type: numeric
    name: "Age at First Birth"

  educ_35:
    type: categorical
    name: "Education (Age 35)"

  inccat_35:
    type: categorical
    name: "Income Category (Age 35)"

  occ_35:
    type: categorical
    name: "Occupation (Age 35)"

  AGE1M:
    type: numeric
    name: "Age at First Marriage"