real_csv: "/home/yx5888/Workspace/AI4SS_Evaluation_local/Simulated_modified/sampled_inputs_gpt-4_temp1.0_top1.0.csv"
sim_csv: "/home/yx5888/Workspace/AI4SS_Evaluation_local/Simulated_modified/sim_profiles_gpt-4_temp1.0_top1.0.csv"

out_dir: "./1111"

bootstrap_B: 1
alpha: 0.05
bootstrap_sample_n: 500

variables:

  self_rated_health:
    type: categorical
    name: "Self-rated Health"
    allowed:
      - Excellent
      - Very Good
      - Good
      - Fair
      - Poor
  self_rated_memory:
    type: categorical
    name: "Self-rated Memory"
    allowed:
      - Excellent
      - Very Good
      - Good
      - Fair
      - Poor

  age_at_first_birth:
    type: numeric
    name: "Age at First Birth"

  educ_35:
    type: categorical
    name: "Education (Age 35)"
    allowed:
      - less than high school
      - high school
      - college and above

  inccat_35:
    type: categorical
    name: "Income Category (Age 35)"
    allowed:
      - lower than 5000
      - 5000 - 9999
      - 10000 - 19999
      - 20000 - 49999
      - 50000+

  occ_35:
    type: categorical
    name: "Occupation (Age 35)"
    allowed:
      - PROFESSIONAL, TECHNICAL AND KINDRED
      - OPERATIVES AND KINDRED
      - MANAGERS, OFFICIALS AND PROPRIETORS
      - SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD
      - CLERICAL AND KINDRED
      - CRAFTSMEN, FOREMEN AND KINDRED
      - SALES WORKERS
      - LABORERS, EXCEPT FARM
      - PRIVATE HOUSEHOLD
      - FARM LABORERS AND FOREMAN

  AGE1M:
    type: numeric
    name: "Age at First Marriage"